### ISSUE TITLE
Parsing solution error

### ISSUE THREAD

**Issue by bernalde** [joehuchette/BARON.jl#19] opened 2018-09-26 23:12 UTC
I stumbled upon a parsing error from BARON while trying to solve a QCQP problem as seen below (sorry for this not being the smallest working example):
`using JuMP, BARON
srand(1234)
m1 = Model(solver = BaronSolver())
n = 5
N = 1
@variable(m1, x[i=1:n])
@variable(m1, aux[i=1:N])
L = Array{Float64,3}(N+1,n,n)
D = Array{Float64,3}(N,n,n)
d = Array{Float64,2}(N,n)
B = Array{Float64,2}(n,n)
b = Array{Float64,1}(n)
for i in 1:(N+1)
    L[i,:,:] = diagm(2*rand(n)-1) + diagm(2*rand(n-1)-1,-1)
    if i <= N
        D[i,:,:] = L[i,:,:]'*L[i,:,:]
        d[i,:] = vec(2*rand(1,n)-1)
    end
end
B = L[N+1,:,:]'*L[N+1,:,:]
b = vec(2*rand(1,n)-1)
@objective(m1, Min, x'*B[:,:]*x/2 + dot(b,x))
for i in 1:N
    S = x'*D[i,:,:]*x + dot(d[i,:],x)
    @constraint(m1, S == aux[i])
    @NLconstraint(m1, aux[i] <= 1)
end
print(m1)
solve(m1)
`

After successfully solving the problem using BARON the following error happens:
`===========================================================================
ERROR: LoadError: ArgumentError: cannot parse "relation" as Float64
Stacktrace:
 [1] parse(::Type{Float64}, ::SubString{String}) at .\parse.jl:203
 [2] read_results(::BARON.BaronMathProgModel) at C:\Users\bernalde\.julia\v0.6\BARON\src\BARON.jl:333
 [3] optimize!(::BARON.BaronMathProgModel) at C:\Users\bernalde\.julia\v0.6\BARON\src\BARON.jl:404
 [4] #solvenlp#165(::Bool, ::Function, ::JuMP.Model, ::JuMP.ProblemTraits) at C:\Users\bernalde\.julia\v0.6\JuMP\src\nlp.jl:1271
 [5] (::JuMP.#kw##solvenlp)(::Array{Any,1}, ::JuMP.#solvenlp, ::JuMP.Model, ::JuMP.ProblemTraits) at .\<missing>:0
 [6] #solve#116(::Bool, ::Bool, ::Bool, ::Array{Any,1}, ::Function, ::JuMP.Model) at C:\Users\bernalde\.julia\v0.6\JuMP\src\solvers.jl:172
 [7] solve(::JuMP.Model) at C:\Users\bernalde\.julia\v0.6\JuMP\src\solvers.jl:150
 [8] include_string(::String, ::String) at .\loading.jl:522
 [9] include_string(::Module, ::String, ::String) at C:\Users\bernalde\.julia\v0.6\Compat\src\Compat.jl:84
 [10] (::Atom.##112#116{String,String})() at C:\Users\bernalde\.julia\v0.6\Atom\src\eval.jl:109
 [11] withpath(::Atom.##112#116{String,String}, ::String) at C:\Users\bernalde\.julia\v0.6\CodeTools\src\utils.jl:30
 [12] withpath(::Function, ::String) at C:\Users\bernalde\.julia\v0.6\Atom\src\eval.jl:38
 [13] hideprompt(::Atom.##111#115{String,String}) at C:\Users\bernalde\.julia\v0.6\Atom\src\repl.jl:67
 [14] macro expansion at C:\Users\bernalde\.julia\v0.6\Atom\src\eval.jl:106 [inlined]
 [15] (::Atom.##110#114{Dict{String,Any}})() at .\task.jl:80
while loading C:\Users\bernalde\Dropbox\CMU\Review\of Convex-Concave Fraction and a Convex Function\BaronBug.jl, in expression starting on line 49`
This seems to be an error of the parser trying to parse a relation (<=, >=, ==) as a float but I couldn't figure out how to fix it.
I'm using JuMP 0.18.2, BARON.jl 0.4.0, BARON 18.8.23, and Julia 0.6.4

**Comment by joehuchette** [comment] 2018-09-29 01:50
I can't reproduce the error on the BARON.jl master branch, can you report the output of ``Pkg.status()``?

**Comment by bernalde** [comment] 2018-09-30 17:59
`27 required packages:
 - AmplNLWriter                  0.4.0
 - Atom                          0.6.17
 - BARON                         0.4.0
 - CPLEX                         0.3.3
 - Clp                           0.5.0
 - Conda                         1.0.2
 - Convex                        0.5.0
 - DataFrames                    0.11.7
 - DifferentialEquations         4.5.0
 - ECOS                          0.9.2
 - Flux                          0.5.4
 - GLPK                          0.8.2
 - Gadfly                        0.8.0
 - Gurobi                        0.5.1
 - Ipopt                         0.4.1
 - JuMP                          0.18.2
 - Juno                          0.4.1
 - Mamba                         0.11.2
 - Mocha                         0.3.1
 - NLopt                         0.3.6
 - Optim                         0.14.1
 - Pajarito                      0.6.0
 - Pavito                        0.1.0
 - Plots                         0.17.4
 - PolyJuMP                      0.2.0
 - PyCall                        1.18.4
 - SCS                           0.4.0
176 additional packages:
...`
I also noticed that the error happens because the variables are not bounded. If I happen to add any bounds to them, the error does not happen.
I tried updated the packages but it still does not solve the problem.
This is not vital for my work, but I just thought you would be interested in fixing any possible bug inside of the parser.

**Comment by joehuchette** [comment] 2018-09-30 21:46
OK, thanks for the additional information. In that case, I believe that this was addressed by d4cb65517aa784502e128aae12c5d34b0b2db511: duals are not available for unbounded problems, and the parser was breaking there. I drafted a new release (https://github.com/JuliaLang/METADATA.jl/pull/18515) which will include this change.

**Closed** 2018-10-07 19:18 UTC
